import Head from "next/head";
import Link from "next/link";
import Menu from "../components/menu";
import util from "../styles/util.module.css";
import ProjectTile from "../components/projectTile";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={util.page}>
        <div className={util.pageColumn}>
          <h1 className={util.header}>Projects</h1>
          <p className={util.description}>
            I invest in companies, and is a part of a few venture communities.
          </p>
          <ul className={util.list}>
            <ProjectTile
              image="compound"
              title="Compound"
              content="This is where I work and spent the past 2y+"
              type="Founding Designer"
              date="2022-05-01"
            />
            <ProjectTile
              image="compound"
              title="Compound"
              content="This is where I work and spent the past 2y+"
              type="Founding Designer"
              date="2022-05-01"
            />
            <ProjectTile
              image="compound"
              title="Compound"
              content="This is where I work and spent the past 2y+"
              type="Founding Designer"
              date="2022-05-01"
            />
          </ul>
        </div>
      </main>
    </>
  );
}
